# signal
MOVING = "MOVING"
STOP = "STOP"
NEED_TO_STOP = "NEED_TO_STOP"
ENTER_INTERSECTION = "ENTER_INTERSECTION"
PASS_INTERSECTION = "PASS_INTERSECTION"
PLATOONING = "PLATOONING"
MOVING_NEXT = "MOVING_NEXT"

# direction
DIR_LEFT = "LEFT"
DIR_RIGHT = "RIGHT"
DIR_DOWN = "DOWN"
DIR_UP = "UP"

# more direction based on the expansion of path
DIR_LEFT_UP = "DIR_LEFT_UP"
DIR_LEFT_DOWN = "DIR_LEFT_DOWN"

DIR_RIGHT_UP = "DIR_RIGHT_UP"
DIR_RIGHT_DOWN = "DIR_RIGHT_DOWN"

DIR_UP_LEFT = "DIR_UP_LEFT"
DIR_UP_RIGHT = "DIR_UP_RIGHT"

DIR_DOWN_LEFT = "DIR_DOWN_LEFT"
DIR_DOWN_RIGHT = "DIR_DOWN_RIGHT"



# flag
READY = "READY"
NOT_READY = "NOT_READY"