# signal
MOVING = "MOVING"
STOP = "STOP"
NEED_TO_STOP = "NEED_TO_STOP"
ENTER_INTERSECTION = "ENTER_INTERSECTION"
PASS_INTERSECTION = "PASS_INTERSECTION"
PLATOONING = "PLATOONING"
MOVING_NEXT = "MOVING_NEXT"

# direction
DIR_LEFT = "LEFT"
DIR_RIGHT = "RIGHT"
DIR_DOWN = "DOWN"
DIR_UP = "UP"

# more direction based on the expansion of path
DIR_LEFT_UP = "LEFT_UP"
DIR_LEFT_DOWN = "LEFT_DOWN"

DIR_RIGHT_UP = "RIGHT_UP"
DIR_RIGHT_DOWN = "RIGHT_DOWN"

DIR_UP_LEFT = "UP_LEFT"
DIR_UP_RIGHT = "UP_RIGHT"

DIR_DOWN_LEFT = "DOWN_LEFT"
DIR_DOWN_RIGHT = "DOWN_RIGHT"


# 4 based path
UP = "UP"
LEFT = "LEFT"
DOWN = "DOWN"
RIGHT = "RIGHT"


# flag
READY = "READY"
NOT_READY = "NOT_READY"

