# signal
MOVING = "MOVING"
STOP = "STOP"
NEED_TO_STOP = "NEED_TO_STOP"
ENTER_INTERSECTION = "ENTER_INTERSECTION"
PASS_INTERSECTION = "PASS_INTERSECTION"
PLATOONING = "PLATOONING"
MOVING_NEXT = "MOVING_NEXT"

# direction
DIR_LEFT = "LEFT"
DIR_RIGHT = "RIGHT"
DIR_DOWN = "DOWN"
DIR_UP = "UP"

# flag
READY = "READY"
NOT_READY = "NOT_READY"